backend:
  name: github
  repo: p440davis/VuePress-Blog-with-Netlify-CMS
media_folder: "blog/.vuepress/public/media"
public_folder: "/media"
publish_mode: editorial_workflow
collections:
  - label: "Posts"
    name: "posts"
    folder: "blog/_posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Summary", name: "summary", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "date" }
      - { label: "Author", name: "author", widget: "string", default: "Me" }
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          default: ["News", "VuePress", "Netlify CMS"],
          hint: "Comma separated list",
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Permalink",
          name: "permalink",
          widget: "hidden",
          default: "/:slug",
        }
