backend:
  name: github
  repo: p440davis/VuePress-Blog-with-Netlify-CMS
media_folder: "blog/.vuepress/public/media"
public_folder: "/media"
publish_mode: editorial_workflow
collections:
  - label: "Posts"
    name: "posts"
    folder: "blog/_posts"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Summary"
        name: "summary"
        widget: "string"
        required: false

      - label: "Publish Date"
        name: "date"
        widget: "date"

      - label: "Author"
        name: "author"
        widget: "select"
        options: [ "Pete Davis", "Billy Chin" ]
        required: false

      - label: "Tags"
        name: "tags"
        widget: "list"
        default: [ "VuePress", "Netlify CMS", "Lorem ipsum", "Food" ]
        hint: "Comma separated list"
        required: false

      - label: "Body"
        name: "body"
        widget: "markdown" 

      - label: "Permalink"
        name: "permalink"
        widget: "hidden"
        default: "/:slug"

